### ISSUE TITLE
Special Characters

### ISSUE THREAD

**Issue by adonisfigueroa** [Lullabot/amp-library#89] opened 2016-06-07 11:37 UTC
Some text with special characters has a wrong parse, for example:

$amp = new AMP();
$amp->loadHtml("You’re there");
echo $amp->convertToAmpHtml();

Or symbols:
$amp->loadHtml("end&#8203;");

Other examples:
première
of ‘A
a – b
Gael García Bernal
-“quotes”-

**Comment by sidkshatriya** [comment] 2016-06-07 12:10
@adonisfigueroa I am not able to repeat the error.

What version of the library are you using? What is the version of PHP? 

```
<?php
require __DIR__.'/vendor/autoload.php';

use Lullabot\AMP\AMP;

$amp = new AMP();
$amp->loadHtml("<p>Gael García Bernal</p>");
echo $amp->convertToAmpHtml();
```

gives
`<p>Gael García Bernal</p>`

**Comment by sidkshatriya** [comment] 2016-06-07 12:11
Can you post your `phpinfo();` perhaps?

**Comment by sidkshatriya** [comment] 2016-06-07 12:15
There was a similar problem sometime ago https://github.com/Lullabot/amp-library/issues/48 which was fixed.

Are you running with the latest versions of the library and its dependencies?

**Comment by adonisfigueroa** [comment] 2016-06-07 12:46
I made un update today (with composer), I have this version:
lullabot/amp               dev-master 02d65f9 A set of useful classes and utilities to convert html to AMP html (See https://www.ampproject.org/)

About the phpinfo, what information do you need specifically?
This is the php version and dom version:

![captura de pantalla de 2016-06-07 14 24 21](https://cloud.githubusercontent.com/assets/3927270/15857746/444c387e-2cbd-11e6-8f7d-9d1ac3a7b404.png)
![captura de pantalla de 2016-06-07 14 22 08](https://cloud.githubusercontent.com/assets/3927270/15857745/444bd884-2cbd-11e6-9a0e-b14430e2ba27.png)

**Comment by sidkshatriya** [comment] 2016-06-07 12:48
@adonisfigueroa 
Do you have mbstring extension installed?

**Comment by adonisfigueroa** [comment] 2016-06-07 12:51
Yes, I have

![captura de pantalla de 2016-06-07 14 49 05](https://cloud.githubusercontent.com/assets/3927270/15858092/163abd32-2cbf-11e6-889a-5aa1cc87dce4.png)

**Comment by sidkshatriya** [comment] 2016-06-07 12:52
What is the output of the small program I posted in https://github.com/Lullabot/amp-library/issues/89#issuecomment-224261277  for you?

**Comment by adonisfigueroa** [comment] 2016-06-07 12:56
Output: Gael GarcÃ­a Bernal

**Comment by sidkshatriya** [comment] 2016-06-07 13:01
This is puzzling for me. What is your operating system? Can you try on another installation of PHP (preferably on LInux or Mac) that you might have access to and tell me what results you are getting?

**Comment by adonisfigueroa** [comment] 2016-06-07 13:15
My localhost is Ubuntu 14.04.4 LTS with php 5.5.9
and in a Red Hat Enterprise Linux Server release 6.7 with php 5.6.21, same results.

**Comment by sidkshatriya** [comment] 2016-06-07 17:07
- Can you tell me what you get when you type `php -i | grep libxml` ?
- Also can you try to run the above https://github.com/Lullabot/amp-library/issues/89#issuecomment-224261277 script in cgi/fpm/fastcgi etc. mode (i.e. non command line) and tell me what output you get?

**Comment by adonisfigueroa** [comment] 2016-06-07 17:17
php -i | grep libxml
libxml Version => 2.9.1
libxml
libxml2 Version => 2.9.1

When execute the code in console, I get correct characters, maybe some problems with charset ISO-8859-1?

/usr/bin/php /var/www/html/test.php

<p>Gael García Bernal</p>

**Comment by sidkshatriya** [comment] 2016-06-07 17:23
Ah! So things are working correctly in the console and _not_ working correctly in the browser?

The AMP library output is UTF-8. We only support UTF-8 output.

**Comment by sidkshatriya** [comment] 2016-06-07 17:23
(We don't support ISO-8859-1)

**Comment by sidkshatriya** [comment] 2016-06-07 17:27
But you can try to do some encoding conversions using [mb_convert_encoding](http://php.net/manual/en/function.mb-convert-encoding.php). Encoding conversions are tricky but ISO-8859-1 is quite a mainstream encoding... 

However, I would advise using UTF-8 for all multilingual stuff in your web pages...

**Comment by adonisfigueroa** [comment] 2016-06-07 17:31
Before submit the issue, I made a test with mb_convert_encoding, but that symbols were unsuccessful, I'll try converting in other way before call to loadHtml.

**Comment by sidkshatriya** [comment] 2016-06-07 17:35
Is there a reason why you must use ISO-8859-1 for your output? UTF-8 is just so much better and you can mix languages other than those supported in latin-1...

**Comment by adonisfigueroa** [comment] 2016-06-07 17:41
Yes, we need to use the AMP in a site with many content in the database that is in ISO-8859-1, then to support UTF-8, we need to convert first all the data.

**Comment by sidkshatriya** [comment] 2016-06-07 17:44
I'm closing this ticket as this not really a bug in the library. The library is working as intended. 

However feel free to keep updating this ticket in case you find something useful or need any help...

**Comment by adonisfigueroa** [comment] 2016-06-07 17:45
Ok thanks for your help

**Closed as completed by sidkshatriya** 2016-06-07 17:44 UTC
Labels: invalid, Phase 2

**Comment by sidkshatriya** [comment] 2016-06-08 04:13
I want to re-word a comment I made above:

> The AMP library output is UTF-8. We only support UTF-8 output.

Actually, it would be more accurate to say is you should only provide UTF-8 input to the library and then you would get proper UTF-8 output. We only support UTF-8 encoding.

**Comment by adonisfigueroa** [comment] 2016-06-08 17:39
It works if the content to UTF-8 is parsed before the call loadHTML and then the results are parsing to initial encoded:

$text = iconv('ISO-8859-1', 'UTF-8//TRANSLIT//IGNORE', $text);
$amp = new AMP();
$amp->loadHtml($text);
$text_amp = $amp->convertToAmpHtml();
$text_amp = iconv('UTF-8', 'ISO-8859-1//TRANSLIT//IGNORE', $text_amp);

Thanks again. You could mention about the encoding supported in the documentation.

**Comment by sidkshatriya** [comment] 2016-06-09 06:56
@adonisfigueroa Thanks for the tip. I have updated `README.md` and added a note saying that we only support UTF-8 and ASCII (UTF-8 is a superset of ASCII).

BTW I'm curious that you chose to use `iconv`. Does `mb_convert_encoding` not do the trick for you?

**Comment by adonisfigueroa** [comment] 2016-06-09 17:20
It was an example, but the good news it's that both work (using it before and after AMP library).

**Comment by adonisfigueroa** [comment] 2016-06-09 17:26
Sorry, an example where it doesn't work with mb_convert_encoding but it works with iconv:
-> special quotes -“What”-
