### ISSUE TITLE
Iframe error

### ISSUE THREAD

**Issue by adonisfigueroa** [Lullabot/amp-library#116] opened 2016-06-29 03:35 UTC
With youtube the parser works fine, but with other iframes it doesn't work:

$amp = new AMP();
$amp->loadHtml("<iframe frameborder=\"0\" height=\"450\" src=\"http://www.kickstarter.com/projects/1081571316/rhino-shield-the-impact-resistant-screen-protector/widget/video.html\" width=\"600\"></iframe>");
echo $amp->convertToAmpHtml();

**Comment by sidkshatriya** [comment] 2016-06-29 11:43
@adonisfigueroa There are no iframes in your your example above. Maybe you forgot to paste something there? (I only see `$amp->loadHtml("");` )

**Comment by adonisfigueroa** [comment] 2016-06-29 11:51
Sorry, I forgot upload as code:

`$amp = new AMP();`
`$amp->loadHtml("<iframe frameborder=\"0\" height=\"450\" src=\"http://www.kickstarter.com/projects/1081571316/rhino-shield-the-impact-resistant-screen-protector/widget/video.html\" width=\"600\"></iframe>");`
`echo $amp->convertToAmpHtml();`

**Comment by sidkshatriya** [comment] 2016-06-29 12:17
@adonisfigueroa In short, your problem is that iframe `src` attribute must be `https` (and not `http`) for the conversion to `<amp-iframe>` to work.

> They must only request resources via HTTPS [...]

See https://github.com/ampproject/amphtml/blob/master/extensions/amp-iframe/amp-iframe.md

These code snippets of yours work but there is a simpler way to trying out things. And that is to use the `amp-console` command line utility. The advantage is that you also easily get warnings.

I created a `test.html` html fragment file

``` html
<iframe frameborder="0" 
  height="450" 
  src="http://www.kickstarter.com/projects/1081571316/rhino-shield-the-impact-resistant-screen-protector/widget/video.html"
  width="600">
</iframe>
```

Now run the fragment through the command line utility

``` html
$ ./amp-console amp:convert test.html 
Line 1: <amp-iframe sandbox="allow-scripts allow-same-origin" layout="responsive" height="450" width="600"></amp-iframe>
Line 2: 
Line 3: 


ORIGINAL HTML
---------------
Line 1: <iframe frameborder="0" 
Line 2:   height="450" 
Line 3:   src="http://www.kickstarter.com/projects/1081571316/rhino-shield-the-impact-resistant-screen-protector/widget/video.html"
Line 4:   width="600">
Line 5: </iframe>
Line 6: 
Line 7: 


Transformations made from HTML tags to AMP custom tags
-------------------------------------------------------

<iframe frameborder height="450" src="http://www.kickstarter.com/projects/1081571316/rhino-shield-the-impact-resistant-screen-protector/widget/video.html" width="600"> at line 4
 ACTION TAKEN: iframe tag was converted to the amp-iframe tag.


AMP-HTML Validation Issues and Fixes
-------------------------------------
FAIL

<amp-iframe sandbox="allow-scripts allow-same-origin" layout="responsive" height="450" width="600" src="http://www.kickstarter.com/projects/1081571316/rhino-shield-the-impact-resistant-screen-protecto... on line 4
- Invalid URL protocol 'http:' for attribute 'src' in tag 'amp-iframe'.
   [code: INVALID_URL_PROTOCOL  category: AMP_TAG_PROBLEM see: https://www.ampproject.org/docs/reference/extended/amp-iframe.html]
   ACTION TAKEN: amp-iframe.src attribute was removed due to validation issues.
```

Note the problem with the INVALID_URL_PROTOCOL flagged as an error. If you change `http` to `https` things will work!

Look at the `README.md` for more examples on using the `amp-console`

**Comment by sidkshatriya** [comment] 2016-06-29 17:42
@adonisfigueroa Even though this is not a bug, this is a good case where the library can "fix" things. In a future branch that is not yet merged, if there is an iframe conversion, it will change the protocol to `https`.

See:
https://github.com/Lullabot/amp-library/commit/197f645587097c4e3bed7ad404ac1d0dd4f865e7

for the relevant change.

Closing.

**Closed as completed by sidkshatriya** 2016-06-29 17:42 UTC
Labels: Phase 2, Works correctly
