### ISSUE TITLE
Youtube iframe embed being stripped out instead of replaced by amp-youtube

### ISSUE THREAD

**Issue by jazzdrive3** [Lullabot/amp-library#97] opened 2016-06-10 19:51 UTC
You can see this in action at http://qa0.runnersworld.com/marine-corps-marathon/watch-marine-corps-marathon-explains-why-you-should-never-swap-bibs

To view the amp version, go to http://qa0.runnersworld.com/marine-corps-marathon/watch-marine-corps-marathon-explains-why-you-should-never-swap-bibs?amp

**Comment by mherchel** [comment] 2016-06-11 13:41
This is weird. I've tested this before on MensHealth (same site within the multisite) and it was working. 

I just copied and pasted the embed code (taken from the source of the page above) into MensHealth (same multisite install) and it worked. Investigating further

`<iframe allowfullscreen="" frameborder="0" height="315" src="https://www.youtube.com/embed/yrW9a1mlIaY" width="500"></iframe>`

**Comment by mherchel** [comment] 2016-06-11 14:00
I can reproduce the problem on my local. When adding `&warnfix=1`, we get 

```
AMP-HTML Validation Issues and Fixes
-------------------------------------
PASS
```

**Comment by mherchel** [comment] 2016-06-11 14:05
The same site is also stripping out embedded images within the body field. My guess is that this is more Drupal than the library. 

Also, we're running version `1.0.0-beta13` of the library.

**Comment by mherchel** [comment] 2016-06-11 14:09
Tracked this down... when I set the input-format of the body field to `full html` it works. To me, this means it's not a library issue.

It looks like a bug in the module. Because `Filtered HTML` does show youtube and images for anonymous users. But, in the AMP view mode, media gets stripped out.

**Comment by mherchel** [comment] 2016-06-11 14:21
Created https://www.drupal.org/node/2747015 to move forward on this. This issue can probably be closed.

**Comment by sidkshatriya** [comment] 2016-06-16 07:53
@mherchel 
I had a chat with Mike a couple of days back on this. The summary discussion was that it is not an AMP library related issue as it seems that `ckeditor` was causing differential behaviour.

But the bottom line is that certain HTML was being removed in `?amp` mode even when there was no amp formatter for that text. `ckeditor` should _not_ cause this effect because it can at most affect HTML as a text _format_. It is not a text _formatter_.

So, I thought about this: the library _could be_ involved if the _whole_ Drupal page is being processed by the library. To confirm this, you simply need to switch off/on the "Power User: Process whole HTML page by library" checkbox (in AMP configuration) and play around with this.

I know Mike has rolled off this project and it sounds like the issue was minor. But in case this is still niggling we can look at this. Note that the library may have nevertheless correctly removed the HTML and for that we would need to see AMP warnings for the whole page in the Drupal reports section.

So depending on what course of action you propose we can either close this issue or proceed further.

cc: @dsayswhat @mtift @jazzdrive3

**Comment by mherchel** [comment] 2016-06-16 13:24
I'm _pretty_ sure I toggled the "Power User: Process whole HTML page by library" checkbox - and didn't see any change in behavior. I deleted the dbs from my local (since they were huge), so I can't test right now.

**Comment by sidkshatriya** [comment] 2016-06-16 13:43
If you togged the power user thing off _and_ were not using any amp formatter but faced the same issue then this is not library related. Closing for now.

**Closed as completed by sidkshatriya** 2016-06-16 13:43 UTC
